name: Apprise

on:
  push:
    paths:
      - .github/workflows/apprise.yaml
      - pyproject.toml
      - uv.lock
      - cyberdrop_dl/utils/apprise.py
      - tests/test_apprise.py
      - tests/test_files/apprise/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/apprise.yaml
      - pyproject.toml
      - uv.lock
      - cyberdrop_dl/utils/apprise.py
      - tests/test_apprise.py
      - tests/test_files/apprise/**
    branches:
      - main
  workflow_dispatch:

jobs:
  test_apprise:
    env:
      APPRISE_TEST_EMAIL_URL: ${{ secrets.APPRISE_TEST_EMAIL_URL }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.10.11"
          python-version: "3.13"

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Run pytest
        run: |
          uv run pytest --cov
