name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'cyberdrop_dl/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/ci.yaml'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'tox.ini'
      - '.python-version'
      - '.github/workflows/apprise.yaml'
      - '.github/workflows/release.yml'
      - 'scripts/release/**'
  pull_request:
    branches:
      - main
    paths:
      - 'cyberdrop_dl/**/*.py'
      - 'cyberdrop_dl/pyproject.toml'
      - 'tests/**/*.py'
      - '.github/workflows/ci.yaml'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'tox.ini'
      - '.python-version'
      - '.github/workflows/apprise.yaml'
      - '.github/workflows/release.yml'
      - 'scripts/release/**'
  workflow_dispatch:

jobs:
  no-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.13, 3.14]
      fail-fast: false

    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.7"
          python-version: ${{ matrix.python-version }}
          enable-cache: "false"
          ignore-empty-workdir: "true"

      - name: Install CDL
        run: uv tool install -v --no-build cyberdrop-dl-patched

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.13, 3.14]
      fail-fast: false

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.7"
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Run pytest
        timeout-minutes: 10
        run: |
          uv run pytest -v --cov
